import React, { useState, useEffect, useRef } from 'react';

/**
 * Question 13: Product List with useState and useEffect
 * 
 * Requirements:
 * - Develop a ReactJS program using useState and useEffect to maintain a list of products
 * - Display a message whenever the product list is modified.
 */
export default function ProductList() {
  const [products, setProducts] = useState([
    { id: 1, name: 'MacBook Pro M3', category: 'Laptops', price: 1999 },
    { id: 2, name: 'Sony WH-1000XM5', category: 'Audio', price: 399 },
    { id: 3, name: 'Keychron K2 Mechanical Keyboard', category: 'Peripherals', price: 89 }
  ]);

  const [notification, setNotification] = useState('');
  const [notificationType, setNotificationType] = useState('info');
  const [notificationHistory, setNotificationHistory] = useState([]);

  // Form input state
  const [name, setName] = useState('');
  const [category, setCategory] = useState('');
  const [price, setPrice] = useState('');

  // Track whether it's initial mount
  const isFirstRender = useRef(true);
  const prevCountRef = useRef(products.length);

  // useEffect hook listening specifically to changes in [products]
  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false;
      const initialMsg = `[useEffect] Component mounted with ${products.length} initial products.`;
      setNotification(initialMsg);
      setNotificationType('info');
      setNotificationHistory((prev) => [
        { id: Date.now(), text: initialMsg, time: new Date().toLocaleTimeString() },
        ...prev
      ]);
      return;
    }

    const currentCount = products.length;
    const diff = currentCount - prevCountRef.current;
    let actionDesc = 'modified';
    if (diff > 0) actionDesc = 'added to';
    else if (diff < 0) actionDesc = 'removed from';

    const msg = `[useEffect Triggered] Product list has been ${actionDesc}! Total items currently: ${currentCount}`;
    setNotification(msg);
    setNotificationType('success');
    setNotificationHistory((prev) => [
      { id: Date.now(), text: msg, time: new Date().toLocaleTimeString() },
      ...prev.slice(0, 4) // keep last 5
    ]);

    prevCountRef.current = currentCount;
  }, [products]);

  const handleAddProduct = (e) => {
    e.preventDefault();
    if (!name.trim() || !price) return;

    const newProd = {
      id: Date.now(),
      name: name.trim(),
      category: category.trim() || 'General',
      price: parseFloat(price)
    };

    setProducts([...products, newProd]);
    setName('');
    setCategory('');
    setPrice('');
  };

  const handleDeleteProduct = (id) => {
    setProducts(products.filter((p) => p.id !== id));
  };

  return (
    <div className="program-container">
      <div className="program-header">
        <h2>Question 13: Product List with useState & useEffect</h2>
        <p className="subtitle">
          Develop a ReactJS program using <code>useState</code> and <code>useEffect</code> to maintain a list of products
          and display a message whenever the product list is modified.
        </p>
      </div>

      {/* Banner displaying message generated by useEffect */}
      {notification && (
        <div className={`notification-banner ${notificationType}`}>
          <div className="notification-icon">🔔</div>
          <div className="notification-content">
            <strong>Notification from useEffect:</strong>
            <p>{notification}</p>
          </div>
        </div>
      )}

      {/* Add Product Form */}
      <div className="card-section">
        <h3>Add New Product</h3>
        <form onSubmit={handleAddProduct} className="inline-form">
          <input
            type="text"
            placeholder="Product Name (e.g. iPad Air)"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
          <input
            type="text"
            placeholder="Category (e.g. Tablets)"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          />
          <input
            type="number"
            step="0.01"
            placeholder="Price ($)"
            value={price}
            onChange={(e) => setPrice(e.target.value)}
            required
          />
          <button type="submit" className="btn btn-primary">➕ Add Product</button>
        </form>
      </div>

      {/* Products Table */}
      <div className="card-section">
        <div className="section-header-flex">
          <h3>Current Products ({products.length})</h3>
        </div>
        {products.length === 0 ? (
          <p className="empty-text">No products in list. Add some above to trigger useEffect!</p>
        ) : (
          <table className="custom-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {products.map((p, idx) => (
                <tr key={p.id}>
                  <td>{idx + 1}</td>
                  <td><strong>{p.name}</strong></td>
                  <td><span className="badge">{p.category}</span></td>
                  <td>${p.price.toFixed(2)}</td>
                  <td>
                    <button
                      onClick={() => handleDeleteProduct(p.id)}
                      className="btn btn-danger-sm"
                    >
                      🗑️ Remove
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Recent useEffect Log History */}
      {notificationHistory.length > 0 && (
        <div className="log-history">
          <h4>Recent useEffect Trigger Logs:</h4>
          <ul>
            {notificationHistory.map((item) => (
              <li key={item.id}>
                <span className="timestamp">[{item.time}]</span> {item.text}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
